use_frameworks!

target 'LGBLocationService_Example' do
  pod 'LGBLocationService', :path => '../'

  target 'LGBLocationService_Tests' do
    pod 'LGBLocationService', :path => '../'

    
  end
end
